export const NATIONALITIES_URI = 'http://localhost:8083/nacionalnost'
export const LEAGUES_URI = 'http://localhost:8083/liga'
export const TEAMS_URI = 'http://localhost:8083/tim'
export const PLAYERS_URI = 'http://localhost:8083/igrac'
export const PLAYER_TEAM_URI = 'http://localhost:8083/igrac/tim'
